import React from 'react';
import {
  CheckCircle2,
  AlertTriangle,
  Clock,
  HelpCircle,
  XCircle,
  ShieldCheck,
  ShieldAlert,
  AlertOctagon
} from 'lucide-react';

export type StatusBadgeVariant =
  | 'validated'
  | 'enriched'
  | 'flagged'
  | 'draft'
  | 'verified'
  | 'candidate'
  | 'missing_evidence'
  | 'rejected'
  | 'unknown'
  | 'conflict';

interface StatusBadgeProps {
  status: string;
  size?: 'sm' | 'md';
  showIcon?: boolean;
  className?: string;
}

export const StatusBadge: React.FC<StatusBadgeProps> = ({
  status,
  size = 'sm',
  showIcon = true,
  className = ''
}) => {
  const norm = (status || '').toLowerCase().trim().replace(/[-\s]+/g, '_');
  const sizeClasses = size === 'sm' ? 'px-2 py-0.5 text-[10px]' : 'px-2.5 py-1 text-xs';
  const iconSize = size === 'sm' ? 'w-3 h-3' : 'w-3.5 h-3.5';

  if (norm === 'validated' || norm === 'verified') {
    return (
      <span
        className={`inline-flex items-center gap-1.5 rounded font-mono font-bold uppercase tracking-wider bg-emerald-950/60 text-emerald-400 border border-emerald-500/40 ${sizeClasses} ${className}`}
        title="Verified against official manufacturer evidence"
      >
        {showIcon && <CheckCircle2 className={`${iconSize} text-emerald-400 flex-shrink-0`} />}
        <span>{norm === 'validated' ? 'Validated' : 'Verified'}</span>
      </span>
    );
  }

  if (norm === 'enriched' || norm === 'candidate') {
    return (
      <span
        className={`inline-flex items-center gap-1.5 rounded font-mono font-bold uppercase tracking-wider bg-cyan-950/50 text-cyan-400 border border-cyan-500/40 ${sizeClasses} ${className}`}
        title="Candidate value generated by pipeline/Gemini (unverified)"
      >
        {showIcon && <Clock className={`${iconSize} text-cyan-400 flex-shrink-0`} />}
        <span>{norm === 'enriched' ? 'Enriched' : 'Candidate'}</span>
      </span>
    );
  }

  if (norm === 'flagged' || norm === 'review_required' || norm === 'needs_review' || norm === 'needs_human_review') {
    return (
      <span
        className={`inline-flex items-center gap-1.5 rounded font-mono font-bold uppercase tracking-wider bg-amber-950/60 text-amber-400 border border-amber-500/40 ${sizeClasses} ${className}`}
        title="Flagged for human review due to low confidence or conflict"
      >
        {showIcon && <ShieldAlert className={`${iconSize} text-amber-400 flex-shrink-0`} />}
        <span>Flagged</span>
      </span>
    );
  }

  if (norm === 'conflict' || norm === 'conflicting') {
    return (
      <span
        className={`inline-flex items-center gap-1.5 rounded font-mono font-bold uppercase tracking-wider bg-rose-950/60 text-rose-400 border border-rose-500/40 ${sizeClasses} ${className}`}
        title="Multiple manufacturer sources contradict on this field"
      >
        {showIcon && <AlertOctagon className={`${iconSize} text-rose-400 flex-shrink-0`} />}
        <span>Conflicting</span>
      </span>
    );
  }

  if (norm === 'rejected') {
    return (
      <span
        className={`inline-flex items-center gap-1.5 rounded font-mono font-bold uppercase tracking-wider bg-rose-950/60 text-rose-400 border border-rose-500/40 ${sizeClasses} ${className}`}
        title="Rejected by specialist or contradicted by evidence"
      >
        {showIcon && <XCircle className={`${iconSize} text-rose-400 flex-shrink-0`} />}
        <span>Rejected</span>
      </span>
    );
  }

  if (norm === 'missing_evidence' || norm === 'no_evidence') {
    return (
      <span
        className={`inline-flex items-center gap-1.5 rounded font-mono font-bold uppercase tracking-wider bg-purple-950/50 text-purple-400 border border-purple-500/40 ${sizeClasses} ${className}`}
        title="No official manufacturer source was found for this attribute"
      >
        {showIcon && <HelpCircle className={`${iconSize} text-purple-400 flex-shrink-0`} />}
        <span>Missing Evidence</span>
      </span>
    );
  }

  if (norm === 'unknown') {
    return (
      <span
        className={`inline-flex items-center gap-1.5 rounded font-mono font-bold uppercase tracking-wider bg-zinc-900 text-zinc-400 border border-zinc-700/60 ${sizeClasses} ${className}`}
        title="Marked unknown to keep field safely blank in export"
      >
        {showIcon && <HelpCircle className={`${iconSize} text-zinc-500 flex-shrink-0`} />}
        <span>Unknown (Blank)</span>
      </span>
    );
  }

  // Draft / Generic Fallback
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded font-mono font-bold uppercase tracking-wider bg-zinc-900 text-zinc-400 border border-zinc-700/60 ${sizeClasses} ${className}`}
    >
      <span>{status || 'Draft'}</span>
    </span>
  );
};
